#!/bin/sh

IS_CONNECTED=$(snapctl is-connected etc-grafana-agent; echo $?)

if [ "${IS_CONNECTED}" = "0" -a -r /etc/grafana-agent.yaml ]
then
  echo "Launched with config from the host filesystem" | systemd-cat
  exec "${SNAP}/agent" -config.file "/etc/grafana-agent.yaml"
else
  echo "Launched with minimal default config from the snap" | systemd-cat
  exec "${SNAP}/agent" -config.file "$SNAP_DATA/etc/grafana-agent.yaml"
fi
