#!/bin/sh

# Get config option
if [ "$(snapctl get reporting-enabled)" = "0" ]
then
  echo "Launching with reporting disabled" | systemd-cat
  REPORTING_ARG="-disable-reporting"
else
  echo "Launching with reporting enabled" | systemd-cat
  REPORTING_ARG=""
fi


launch_classic() {

  echo "Launching with config from the host filesystem" | systemd-cat
  exec "${SNAP}/agent" -config.expand-env -config.file "/etc/grafana-agent.yaml" "${REPORTING_ARG}"  

}


launch_strict() {
  
  IS_CONNECTED=$(snapctl is-connected etc-grafana-agent; echo $?)

  if [ "${IS_CONNECTED}" = "0" ] && [ -r /etc/grafana-agent.yaml ]
  then
    echo "Launching with config from the host filesystem" | systemd-cat
    CONFIG_FILE="/etc/grafana-agent.yaml"
  else
    echo "Launching with minimal default config from the snap" | systemd-cat
    CONFIG_FILE="$SNAP_DATA/etc/grafana-agent.yaml"
  fi

  exec "${SNAP}/agent" -config.expand-env -config.file "${CONFIG_FILE}" "${REPORTING_ARG}"

}


# Detect confinement type
# https://forum.snapcraft.io/t/reliable-way-of-detecting-snap-confinement-mode/8896/4
IS_CLASSIC=$(grep -qxF "confinement: classic" "$SNAP/meta/snap.yaml"; echo $?)
if [ "${IS_CLASSIC}" = "0" ]
then
  launch_classic
else
  launch_strict
fi
