#!/bin/sh

IS_CONNECTED=$(snapctl is-connected etc-grafana-agent; echo $?)

if [ "${IS_CONNECTED}" = "0" -a -r /etc/grafana-agent.yaml ]
then
  echo "Launched with config from the host filesystem" | systemd-cat
  CONFIG_FILE="/etc/grafana-agent.yaml"
else
  echo "Launched with minimal default config from the snap" | systemd-cat
  CONFIG_FILE="$SNAP_DATA/etc/grafana-agent.yaml"
fi

if [ "$(snapctl get reporting_enabled)" = "0" ]
then
  REPORTING_ARG="-disable-reporting"
else
  REPORTING_ARG=""
fi

exec "${SNAP}/agent" -config.expand-env -config.file "${CONFIG_FILE}" "${REPORTING_ARG}"
