name: grafana-agent
version: '0.33.0'
summary: A telemetry collector for sending metrics, logs, and trace data
license: Apache-2.0
contact: simon.aronsson@canonical.com
issues: https://github.com/simskij/grafana-agent/issues
source-code: https://github.com/simskij/grafana-agent
website: https://grafana.com
description: "Grafana Agent is a telemetry collector for sending metrics, \nlogs, and trace data to the opinionated Grafana observability stack.\n"
base: core22
grade: stable
confinement: strict
compression: lzo
plugs:
  etc-grafana-agent:
    interface: system-files
    read:
      - /etc/grafana-agent.yaml
  logs:
    interface: content
    target: $SNAP/shared-logs
  proc-sys-kernel-random:
    interface: system-files
    read:
      - /proc/sys/kernel/random/write_wakeup_threshold
      - /proc/sys/kernel/random/read_wakeup_threshold
      - /proc/sys/kernel/random/poolsize
      - /proc/sys/kernel/random/urandom_min_reseed_secs
apps:
  grafana-agent:
    daemon: simple
    command: agent-wrapper
    install-mode: disable
    restart-condition: on-failure
    plugs:
      - network-bind
      - time-control
      - hardware-observe
      - mount-observe
      - network-observe
      - system-observe
      - log-observe
      - etc-grafana-agent
      - proc-sys-kernel-random
architectures:
  - build-on: amd64
parts:
  wrapper:
    plugin: dump
    source: ./snap/local
    source-type: local
    override-build: |
      cp agent-wrapper $CRAFT_PART_INSTALL/
  grafana-agent:
    plugin: go
    source: https://github.com/grafana/agent
    source-type: git
    source-tag: "v0.33.0"
    build-packages:
      - build-essential
      - golang
      - libsystemd-dev
      - libbpfcc-dev
      - bpfcc-tools
    stage-packages:
      - libsystemd0
      - libbpfcc
      - bpfcc-tools
    build-environment:
      - USE_CONTAINER: 0
      - GOFLAGS: "-mod=readonly"
    override-build: |
      make agent agentctl
      cp build/agent $CRAFT_PART_INSTALL/
      cp build/agentctl $CRAFT_PART_INSTALL/
