name: Pull Request

on:
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request:
    uses: canonical/observability/.github/workflows/snap-pull-request.yaml@v2
