name: Update Snap on new releases of its source

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    uses: canonical/observability/.github/workflows/snap-update.yaml@v2
    with:
      source-repo: grafana/agent
    secrets:
      OBSERVABILITY_NOCTUA_TOKEN: ${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}
      NOCTUA_GPG_PASSPHRASE: ${{ secrets.NOCTUA_GPG_PASSPHRASE }}
      NOCTUA_GPG_PRIVATE: ${{ secrets.NOCTUA_GPG_PRIVATE }}
